### ISSUE TITLE
I cannot find the package in package control

### ISSUE THREAD

**Issue by stdedos** [akatopo/GithubEmoji#1]
It may not be an issue related here, but still, I thought I should raise it here.
This is my PackageControl image:
![screenshot 2016-01-19 12 16 27](https://cloud.githubusercontent.com/assets/133706/12415843/8fbb5d92-bea6-11e5-96cb-9f0389488503.png)

**Comment by akatopo** [comment]
Strange, are you by any chance using Sublime Text 2? This package works only in ST3

**Comment by stdedos** [comment]
No, I use Stable Build, 3083

Ντέντος Σταύρος

**Comment by akatopo** [comment]
I think I've found what the problem is. Your package control must be not updating the package list. See how package versions are mismatched?

Try [reinstalling](https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling) package control, that should do the trick :ok_hand: 

![package-control](https://cloud.githubusercontent.com/assets/2387645/12770405/d55437ec-ca28-11e5-9a82-96eef25fccd9.png)

**Comment by stdedos** [comment]
I confirm it was my mistake (Error in channel configuration - I had the
webarchive .js file since the server was down)
Το παρόν email στάλθηκε από ασφαλή υπολογιστή που προστατεύεται από το
Avast.
www.avast.com https://www.avast.com/sig-email
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Ντέντος Σταύρος
